box.cfg{listen=3324}
box.space.file:drop()
box.sequence.S:drop()
box.space.clients:drop()
box.sequence.SC:drop()
box.schema.space.create('file',{id=24})
box.schema.sequence.create('S',{min=1, start=1})
box.space.file:create_index('I',{sequence='S'})
box.schema.space.create('clients',{id=25})
box.schema.sequence.create('SC',{min=1, start=1})
box.space.clients:create_index('I',{sequence='SC'})
--box.schema.user.grant('guest', 'read,write,execute', 'universe')
